// Generated by CoffeeScript 1.12.7
(function() {
  describe('lib/gbemu', function() {
    return it('can test something', function() {
      var cpu;
      cpu = new CPU;
      return expect(cpu.register.A).toBe(0);
    });
  });

}).call(this);
